language: node_js
node_js:
  - "0.11"
after_success:
  - "lsb_release -a"
  - "sudo apt-get install build-essential"
  - "sudo apt-add-repository -y ppa:brightbox/ruby-ng"
  - "sudo apt-get update"
  - "sudo apt-get install ruby2.1 ruby2.1-dev"
  - "sudo update-alternatives --set ruby /usr/bin/ruby2.1"    
  - "sudo apt-get install libgemplugin-ruby"
  - "sudo gem install tilt"
  - "sudo gem install azure"
  - "sudo gem install net-ssh"
  - "sudo gem install net-scp"
  - "sudo gem install winrm"
  - "sudo gem install highline"
  - "sudo wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.3_x86_64.deb"
  - "sudo dpkg -i vagrant_1.6.3_x86_64.deb"
  - "sudo vagrant plugin install vagrant-azure"
  - "sudo vagrant box add azure https://github.com/msopentech/vagrant-azure/raw/master/dummy.box"
  - "sudo mkdir vagrant-project"
  - "cd vagrant-project/"
  - "sudo vagrant init azure"
  - "cd ~"
  - "sudo gem install puppet"
  - "sudo puppet resource package puppet ensure=latest provider=gem"
  - "sudo which puppet"
  - "sudo dpkg -s puppet"
  - "sudo puppet module install msopentech-windowsazure"
  - "sudo wget 'https://pigdemo.blob.core.windows.net/pigdemo/elasta.pem?sr=b&sv=2014-02-14&st=2014-07-08T09%3A45%3A49Z&se=2015-03-31T10%3A45%3A49Z&sp=r&sig=GOXiXVwY%2Fr%2FC99pmuGZe40MTPaPDTCqNt0jlbD7CBE4%3D' -O elasta.pem"
  - "ls -la"
  - "sudo puppet azure_vm create --management-certificate ./elasta.pem --azure-subscription-id 5191b16a-673d-426c-8c55-fdd912858e4e --image b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04-LTS-amd64-server-20140416.1-en-us-30GB --vm-name puppet1-oddkinz-armcs-02 --vm-user jed --password 'P@ssword761' --ssh-port=22 --storage-account-name mtlytics --cloud-service-name=armcs-02 --deployment-name=armcs-02 --location 'North Europe'"
  - "sleep 360"
  - "sudo puppet azure_vm bootstrap --puppet-master-ip=elastapuppet.cloudapp.net --ssh-user=jed --ssh-port=22 --password=P@ssword761 --node-ipaddress armcs-02.cloudapp.net --ssh-port=22"
  - "sudo puppet azure_vm add_role --management-certificate ./elasta.pem --azure-subscription-id 5191b16a-673d-426c-8c55-fdd912858e4e --image b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04-LTS-amd64-server-20140416.1-en-us-30GB --vm-name puppet2-oddkinz-armcs-02 --vm-user jed --password 'P@ssword761' --cloud-service-name armcs-02 --storage-account-name mtlytics --ssh-port=23"
  - "sleep 360"
  - "sudo puppet azure_vm bootstrap --puppet-master-ip=elastapuppet.cloudapp.net --ssh-user=jed --ssh-port=22 --password=P@ssword761 --node-ipaddress armcs-02.cloudapp.net --ssh-port=23"
  - "sudo puppet azure_vm update_endpoint --management-certificate ./elasta.pem --azure-subscription-id 5191b16a-673d-426c-8c55-fdd912858e4e --cloud-service-name=armcs-02 --endpoint-name=arm-cs --load-balanced-endpoint='fred' --local-port=80 --load-balancer-port=80 --vm-name puppet1-oddkinz-armcs-02"
  - "sudo puppet azure_vm update_endpoint --management-certificate ./elasta.pem --azure-subscription-id 5191b16a-673d-426c-8c55-fdd912858e4e --cloud-service-name=armcs-02 --endpoint-name=arm-cs --load-balanced-endpoint='fred' --local-port=80 --load-balancer-port=80 --vm-name puppet2-oddkinz-armcs-02"
