language: node_js
node_js:
  - "0.11"
after_success:
  - "sudo apt-get install build-essential"
  - "sudo apt-add-repository ppa:brightbox/ruby-ng"
  - "sudo apt-get update"
  - "sudo apt-get install ruby2.1 ruby2.1-dev"
  - "sudo update-alternatives --set ruby /usr/bin/ruby2.1"
  - "sudo apt-get install libgemplugin-ruby"
  - "sudo apt-get install puppet"
  - "sudo gem install tilt"
  - "sudo gem install azure"
  - "sudo gem install net-ssh"
  - "sudo gem install net-scp"
  - "sudo gem install winrm"
  - "sudo gem install highline"